#include "esphome/core/log.h"
#include "clockwise_component.h"
// Auto-generated by __init__.py -- registers all configured clockfaces
#include "clockface_registry.h"

namespace esphome {
namespace clockwise_component {

static const char *TAG = "clockwise_component.component";

void ClockwiseComponent::setup() {
    _gfxWrapper = new ESPHomeGFXWrapper(
        _matrixDisplay,
        _matrixDisplay->get_width(),
        _matrixDisplay->get_height()
    );
    _gfxWrapper->setTextWrap(false);

    _cwDateTime = new CWDateTimeESPTime(_rtc);

    // Register all clockfaces (function defined in clockface_registry.h)
    registerAllFaces(_manager, _gfxWrapper);

    // Initialize manager with time reference
    _manager.init(_cwDateTime);

    ESP_LOGCONFIG(TAG, "ClockwiseComponent ready with %d face(s)", _manager.count());
}

void ClockwiseComponent::draw() {
    _manager.update();
}

void ClockwiseComponent::loop() { }

void ClockwiseComponent::dump_config() {
    ESP_LOGCONFIG(TAG, "ClockwiseComponent with %d clockface(s)", _manager.count());
    ESP_LOGCONFIG(TAG, "  Active face: %s", _manager.activeName());
}

}  // namespace clockwise_component
}  // namespace esphome
