#pragma once

#include "clockface_manager.h"
#include <Adafruit_GFX.h>

// STUB: This header will be auto-generated by __init__.py (Task 3).
// For now, it provides an empty registerAllFaces() so the component compiles.
// The auto-generated version will include submodule wrappers and register them.

inline void registerAllFaces(ClockfaceManager& /*manager*/, Adafruit_GFX* /*gfx*/) {
    // No clockfaces registered yet. Task 3 will populate this via codegen.
}
