#include "esphome/core/log.h"
#include "clockwise_component.h"
#ifdef USE_ESP32
#include "esphome/components/hub75/hub75_component.h"
#endif
// Auto-generated by __init__.py -- registers all configured clockfaces
#include "clockface_registry.h"

namespace esphome {
namespace clockwise_component {

static const char *TAG = "clockwise_component.component";

void ClockwiseComponent::setup() {
  _gfxWrapper = new ESPHomeGFXWrapper(
    _matrixDisplay,
    _matrixDisplay->get_width(),
    _matrixDisplay->get_height()
  );
  _gfxWrapper->setTextWrap(false);

  _cwDateTime = new CWDateTimeESPTime(_rtc);

  // Register all clockfaces (function defined in clockface_registry.h)
  registerAllFaces(_manager, _gfxWrapper);

  // Initialize manager with time reference
  _manager.init(_cwDateTime);

  // Disable HUB75 auto-flip; manual flip in draw() ensures back buffer always becomes visible
#ifdef USE_ESP32
  if (auto* hub = static_cast<esphome::hub75::HUB75Display*>(_matrixDisplay)) {
    hub->setAutoFlip(false);
  }
#endif
  ESP_LOGCONFIG(TAG, "Clockwise ready %d faces (House needs DB: %s)", _manager.count(), _manager.activeNeedsDoubleBuffer() ? "yes" : "no");
}

void ClockwiseComponent::draw() {
#ifdef USE_ESP32
  // For incremental faces (Mario/Pacman) that don't redraw full screen,
  // seed back buffer from front before drawing delta to avoid flicker
  // between stale House and current frame. House does full redraw, so copy is optional.
  if (!shouldFlip()) {
    if (auto* hub = static_cast<esphome::hub75::HUB75Display*>(_matrixDisplay)) hub->copy_front_to_back();
  }
#endif
  _manager.update();
  tryFlip();
}

void ClockwiseComponent::tryFlip() {
#ifdef USE_ESP32
  // Always flip when double buffering is enabled — selective gating caused
  // freeze for non-House faces (back buffer never became visible).
  // Per-face needsDoubleBuffer remains for future lazy allocation, not flip gating.
  if (auto* hub = static_cast<esphome::hub75::HUB75Display*>(_matrixDisplay)) hub->flip_buffer();
#endif
}

void ClockwiseComponent::loop() {}

void ClockwiseComponent::dump_config() {
  ESP_LOGCONFIG(TAG, "ClockwiseComponent with %d clockface(s)", _manager.count());
  ESP_LOGCONFIG(TAG, "  Active face: %s", _manager.activeName());
}

}  // namespace clockwise_component
}  // namespace esphome
