#include "esphome/core/log.h"
#include "clockwise_component.h"
#include "esphome/components/hub75/hub75_component.h"
// Auto-generated by __init__.py -- registers all configured clockfaces
#include "clockface_registry.h"

namespace esphome {
namespace clockwise_component {

static const char *TAG = "clockwise_component.component";

void ClockwiseComponent::setup() {
  _gfxWrapper = new ESPHomeGFXWrapper(
    _matrixDisplay,
    _matrixDisplay->get_width(),
    _matrixDisplay->get_height()
  );
  _gfxWrapper->setTextWrap(false);

  _cwDateTime = new CWDateTimeESPTime(_rtc);

  // Register all clockfaces (function defined in clockface_registry.h)
  registerAllFaces(_manager, _gfxWrapper);

  // Initialize manager with time reference
  _manager.init(_cwDateTime);

  // Disable auto-flip; we will flip selectively in draw()
  if (auto* hub = (esphome::hub75::HUB75Display*)_matrixDisplay) {
    hub->setAutoFlip(false);
  }
  ESP_LOGCONFIG(TAG, "Clockwise ready %d faces (House needs DB: %s)", _manager.count(), _manager.activeNeedsDoubleBuffer() ? "yes" : "no");
}

void ClockwiseComponent::draw() {
  _manager.update();
  if (shouldFlip()) {
    if (auto* hub = (esphome::hub75::HUB75Display*)_matrixDisplay) hub->flip_buffer();
  }
}

void ClockwiseComponent::tryFlip() {
  if (shouldFlip()) {
    if (auto* hub = (esphome::hub75::HUB75Display*)_matrixDisplay) hub->flip_buffer();
  }
}

void ClockwiseComponent::loop() { }

void ClockwiseComponent::dump_config() {
    ESP_LOGCONFIG(TAG, "ClockwiseComponent with %d clockface(s)", _manager.count());
    ESP_LOGCONFIG(TAG, "  Active face: %s", _manager.activeName());
}

}  // namespace clockwise_component
}  // namespace esphome
